export const formSections = [
  {
    title: "Personal Information",
    fields: [
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        required: true,
        placeholder: "Enter your full name",
        width: "full",
      },
      {
        name: "age",
        label: "Age",
        type: "number",
        required: true,
        placeholder: "Enter your age",
        width: "half",
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Male", "Female", "Other"],
        required: true,
        width: "half",
      },
      {
        name: "height",
        label: "Height (in cm)",
        type: "number",
        required: true,
        placeholder: "Enter height in centimeters",
        width: "half",
      },
      {
        name: "weight",
        label: "Weight (in kg)",
        type: "number",
        required: true,
        placeholder: "Enter weight in kilograms",
        width: "half",
      },
      {
        name: "email",
        label: "Email Address",
        type: "email",
        required: true,
        placeholder: "Enter your email",
        width: "full",
      },
      {
        name: "phoneNumber",
        label: "Phone Number",
        type: "text",
        required: true,
        placeholder: "Enter your phone number",
        width: "full",
      },
      {
        name: "location",
        label: "Location and Time Zone",
        type: "text",
        required: true,
        placeholder: "Enter your location and time zone",
        width: "full",
      },
    ],
  },
  {
    title: "Fitness Goals",
    fields: [
      {
        name: "fitnessGoals",
        label: "What are your primary fitness goals?",
        type: "checkbox",
        options: [
          "Weight loss",
          "Muscle building",
          "Improved strength",
          "Better endurance",
          "Improved flexibility",
          "Pain or injury management",
          "General health and fitness",
          "Other",
        ],
        required: true,
        width: "full",
      },
      {
        name: "motivation",
        label: "What motivates you to achieve this goal?",
        type: "textarea",
        required: true,
        placeholder: "Describe your motivation",
        width: "full",
      },
      {
        name: "resultsTimeline",
        label: "How soon are you looking to see noticeable results?",
        type: "text",
        required: true,
        placeholder: "Enter your timeline",
        width: "full",
      },
    ],
  },
  {
    title: "Medical History",
    fields: [
      {
        name: "medicalConditions",
        label: "Do you have any medical conditions, injuries, or chronic pain?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "medicalDetails",
        label: "If yes, please provide details",
        type: "textarea",
        required: false,
        placeholder: "Describe any medical conditions",
        width: "full",
      },
      {
        name: "medications",
        label: "Are you currently taking any medications?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "medicationDetails",
        label: "If yes, please list them",
        type: "textarea",
        required: false,
        placeholder: "List medications",
        width: "full",
      },
      {
        name: "surgeries",
        label: "Have you undergone any recent surgeries or treatments?",
        type: "textarea",
        required: false,
        placeholder: "Provide details of surgeries or treatments",
        width: "full",
      },
      {
        name: "foodAllergies",
        label: "Do you have any food allergies or intolerances?",
        type: "textarea",
        required: false,
        placeholder: "List food allergies or intolerances",
        width: "full",
      },
    ],
  },
  {
    title: "Current Lifestyle and Fitness Routine",
    fields: [
      {
        name: "lifestyleActivity",
        label: "How active is your current lifestyle?",
        type: "select",
        options: [
          "Sedentary (little or no exercise)",
          "Lightly active (light exercise 1-2 days/week)",
          "Moderately active (moderate exercise 3-4 days/week)",
          "Very active (hard exercise 5+ days/week)",
        ],
        required: true,
        width: "full",
      },
      {
        name: "fitnessExperience",
        label: "Do you have any prior experience with fitness training?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "fitnessDetails",
        label: "If yes, what kind (e.g., gym workouts, running, yoga)?",
        type: "textarea",
        required: false,
        placeholder: "Provide details of fitness experience",
        width: "full",
      },
      {
        name: "routineConsistency",
        label: "How consistent are you with your current fitness routine?",
        type: "text",
        required: true,
        placeholder: "Describe your consistency",
        width: "full",
      },
      {
        name: "exerciseTime",
        label: "What time of the day do you prefer to exercise?",
        type: "select",
        options: ["Morning", "Afternoon", "Evening", "Night"],
        required: true,
        width: "full",
      },
    ],
  },
  {
    title: "Dietary Preferences",
    fields: [
      {
        name: "dietType",
        label: "What is your typical diet like?",
        type: "text",
        required: true,
        placeholder: "e.g., vegetarian, non-vegetarian, vegan",
        width: "full",
      },
      {
        name: "dietaryPractices",
        label: "Do you follow any specific dietary practices or restrictions?",
        type: "textarea",
        required: false,
        placeholder: "List dietary practices or restrictions",
        width: "full",
      },
      {
        name: "mealsPerDay",
        label: "How many meals and snacks do you typically have in a day?",
        type: "number",
        required: true,
        placeholder: "Enter number of meals/snacks",
        width: "full",
      },
      {
        name: "favoriteFoods",
        label: "What are your favorite foods or cuisines?",
        type: "textarea",
        required: false,
        placeholder: "List favorite foods or cuisines",
        width: "full",
      },
      {
        name: "dislikedFoods",
        label: "Are there any foods you dislike or wish to avoid?",
        type: "textarea",
        required: false,
        placeholder: "List disliked foods",
        width: "full",
      },
    ],
  },
  {
    title: "Training Preferences",
    fields: [
      {
        name: "equipmentAccess",
        label: "Do you have access to any fitness equipment at home?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "equipmentDetails",
        label: "If yes, please specify",
        type: "textarea",
        required: false,
        placeholder: "List fitness equipment",
        width: "full",
      },
      {
        name: "workoutTime",
        label: "How much time can you dedicate to workouts daily?",
        type: "text",
        required: true,
        placeholder: "Enter time in minutes/hours",
        width: "full",
      },
      {
        name: "trainingStyle",
        label: "Do you have any specific preferences for training styles?",
        type: "textarea",
        required: false,
        placeholder: "e.g., HIIT, yoga, strength training",
        width: "full",
      },
      {
        name: "dislikedExercises",
        label:
          "Are there any exercises or movements you dislike or find uncomfortable?",
        type: "textarea",
        required: false,
        placeholder: "List disliked exercises",
        width: "full",
      },
    ],
  },
  {
    title: "Expectations from Online Training",
    fields: [
      {
        name: "trainingExpectations",
        label: "What do you expect from your online personal training program?",
        type: "checkbox",
        options: [
          "Personalized workout plans",
          "Nutrition guidance",
          "Regular check-ins",
          "Progress tracking",
          "Other",
        ],
        required: true,
        width: "full",
      },
      {
        name: "communicationPreference",
        label: "How would you like to communicate with your trainer?",
        type: "text",
        required: true,
        placeholder: "e.g., video calls, chat, email",
        width: "full",
      },
      {
        name: "challenges",
        label:
          "What challenges do you think might affect your fitness journey?",
        type: "textarea",
        required: false,
        placeholder: "Describe challenges",
        width: "full",
      },
    ],
  },
  {
    title: "Lifestyle & Routine",
    fields: [
      {
        name: "typicalDay",
        label:
          "What does a typical day look like for you? (Work hours, physical activities, etc.)",
        type: "textarea",
        required: false,
        placeholder: "Describe your daily routine",
        width: "full",
      },
      {
        name: "sleepHours",
        label: "How many hours of sleep do you get on average per night?",
        type: "number",
        required: false,
        placeholder: "e.g., 7",
        width: "full",
      },
      {
        name: "sleepSchedule",
        label:
          "What is your usual sleep schedule? (Time you go to bed and wake up)",
        type: "text",
        required: false,
        placeholder: "e.g., 10:00 PM to 6:00 AM",
        width: "full",
      },
      {
        name: "wakeUpFeel",
        label:
          "How do you usually feel when you wake up? (Refreshed, tired, etc.)",
        type: "text",
        required: false,
        placeholder: "e.g., Refreshed",
        width: "full",
      },
      {
        name: "exerciseFrequency",
        label:
          "How often do you exercise or engage in physical activity? (Type and frequency)",
        type: "textarea",
        required: false,
        placeholder: "e.g., Jogging 3 times a week",
        width: "full",
      },
      {
        name: "workoutChallenges",
        label:
          "Do you face any challenges with maintaining a consistent workout routine? (If yes, explain)",
        type: "textarea",
        required: false,
        placeholder: "Describe challenges if any",
        width: "full",
      },
      {
        name: "sedentaryLifestyle",
        label: "Do you have a sedentary job or lifestyle? (Yes/No)",
        type: "text",
        required: false,
        placeholder: "Yes or No",
        width: "full",
      },
    ],
  },
  {
    title: "Dietary Preferences & Habits",
    fields: [
      {
        name: "dietType",
        label:
          "Are you vegetarian, non-vegetarian, vegan, or follow another specific diet?",
        type: "text",
        required: true,
        placeholder: "e.g., Vegetarian",
        width: "full",
      },
      {
        name: "foodLikesDislikes",
        label:
          "What types of foods do you like or dislike? (e.g., spicy, sweet, savory)",
        type: "textarea",
        required: false,
        placeholder: "Describe likes and dislikes",
        width: "full",
      },
      {
        name: "typicalMeals",
        label:
          "What are your typical meals during the day? (Breakfast, lunch, dinner, snacks)",
        type: "textarea",
        required: false,
        placeholder: "e.g., Breakfast: Oats, Lunch: Rice and vegetables",
        width: "full",
      },
      {
        name: "mealPreparation",
        label: "Do you often eat out or cook at home?",
        type: "text",
        required: false,
        placeholder: "e.g., Cook at home",
        width: "full",
      },
      {
        name: "mealPreference",
        label: "Do you prefer smaller, frequent meals or larger meals?",
        type: "text",
        required: false,
        placeholder: "e.g., Smaller frequent meals",
        width: "full",
      },
      {
        name: "dietarySupplements",
        label:
          "Do you consume any dietary supplements? (Protein, vitamins, etc.)",
        type: "text",
        required: false,
        placeholder: "e.g., Protein powder",
        width: "full",
      },
      {
        name: "foodAllergies",
        label:
          "Do you have any food allergies or intolerances? (e.g., gluten, dairy)",
        type: "text",
        required: false,
        placeholder: "e.g., Lactose intolerant",
        width: "full",
      },
      {
        name: "digestiveIssues",
        label:
          "Do you have any digestive issues? (Indigestion, bloating, acid reflux, etc.)",
        type: "text",
        required: false,
        placeholder: "Describe any issues",
        width: "full",
      },
      {
        name: "mealsPerDay",
        label: "How many meals and snacks do you usually eat in a day?",
        type: "number",
        required: false,
        placeholder: "e.g., 3 meals, 2 snacks",
        width: "full",
      },
      {
        name: "alcoholSmoking",
        label: "Do you drink alcohol or smoke? (If yes, how often?)",
        type: "textarea",
        required: false,
        placeholder: "Describe frequency",
        width: "full",
      },
    ],
  },
  {
    title: "Mindset & Consistency",
    fields: [
      {
        name: "pastDietPlans",
        label:
          "Have you followed any diet plans in the past? (If yes, which ones?)",
        type: "textarea",
        required: false,
        placeholder: "e.g., Keto, Intermittent Fasting",
        width: "full",
      },
      {
        name: "dietPlanFeedback",
        label: "What worked or didn’t work for you with previous diet plans?",
        type: "textarea",
        required: false,
        placeholder: "Describe your experience",
        width: "full",
      },
      {
        name: "consistencyChallenges",
        label:
          "What challenges do you face in staying consistent with a diet or training plan?",
        type: "textarea",
        required: false,
        placeholder: "Describe challenges if any",
        width: "full",
      },
      {
        name: "preferredDietPlan",
        label:
          "What kind of diet plan do you think you could follow consistently for long-term success?",
        type: "textarea",
        required: false,
        placeholder: "e.g., Balanced with occasional treats",
        width: "full",
      },
      {
        name: "dietingApproach",
        label:
          "Do you believe in strict dieting, or would you prefer a flexible approach?",
        type: "text",
        required: false,
        placeholder: "e.g., Flexible approach",
        width: "full",
      },
    ],
  },
  {
    title: "Health & Medical Information",
    fields: [
      {
        name: "currentMedicalConditions",
        label:
          "Do you have any current or past medical conditions? (Diabetes, high blood pressure, etc.)",
        type: "textarea",
        required: false,
        placeholder: "List conditions if any",
        width: "full",
      },
      {
        name: "currentMedications",
        label: "Are you currently taking any medications or supplements?",
        type: "textarea",
        required: false,
        placeholder: "e.g., Multivitamins, Blood pressure meds",
        width: "full",
      },
      {
        name: "familyHealthHistory",
        label:
          "Do you have any family history of health conditions that might affect your diet? (e.g., heart disease, obesity)",
        type: "textarea",
        required: false,
        placeholder: "e.g., Family history of diabetes",
        width: "full",
      },
      {
        name: "pastInjuries",
        label: "Have you experienced any injuries or surgeries in the past?",
        type: "textarea",
        required: false,
        placeholder: "e.g., Knee surgery in 2020",
        width: "full",
      },
      {
        name: "digestiveMetabolicIssues",
        label:
          "Do you have any issues with digestion, metabolism, or energy levels?",
        type: "textarea",
        required: false,
        placeholder: "e.g., Low energy in afternoons",
        width: "full",
      },
      {
        name: "specificHealthGoals",
        label:
          "Are there any specific health goals you are working on? (e.g., weight loss, managing blood sugar)",
        type: "textarea",
        required: false,
        placeholder: "e.g., Weight loss of 10kg",
        width: "full",
      },
    ],
  },
  {
    title: "Goals & Expectations",
    fields: [
      {
        name: "mainGoals",
        label:
          "What are your main health and fitness goals? (Weight loss, muscle gain, improve energy, etc.)",
        type: "textarea",
        required: true,
        placeholder: "e.g., Muscle gain and increased stamina",
        width: "full",
      },
      {
        name: "goalTimeline",
        label: "What timeline do you have in mind for achieving your goals?",
        type: "text",
        required: false,
        placeholder: "e.g., 6 months",
        width: "full",
      },
      {
        name: "balancedDietDefinition",
        label: "How do you define a balanced and sustainable diet?",
        type: "textarea",
        required: false,
        placeholder: "Describe your perspective",
        width: "full",
      },
      {
        name: "shortLongTermGoals",
        label:
          "Do you have any short-term or long-term weight or fitness goals?",
        type: "textarea",
        required: false,
        placeholder: "e.g., Short-term: Lose 5kg; Long-term: Build muscle",
        width: "full",
      },
      {
        name: "motivationScale",
        label:
          "How motivated are you to make dietary changes? (On a scale of 1-10)",
        type: "number",
        required: true,
        placeholder: "e.g., 8",
        width: "full",
      },
    ],
  },
  {
    title: "Additional Information",
    fields: [
      {
        name: "additionalInfo",
        label:
          "Is there anything else you would like us to know that may help us create the right nutrition plan for you?",
        type: "textarea",
        required: false,
        placeholder: "Add any additional details here",
        width: "full",
      },
    ],
  },
];

const fields = formSections.map((field) => {
  return field.fields.length;
});

export const totalQuestions = fields.reduce((acc, item) => {
  return acc + item;
}, 0);
