export const formSections = [
  {
    title: "Personal Information",
    fields: [
      {
        name: "fullName",
        label: "Full Name",
        type: "text",
        required: true,
        placeholder: "Enter your full name",
        width: "full",
      },
      {
        name: "age",
        label: "Age",
        type: "number",
        required: true,
        placeholder: "Enter your age",
        width: "half",
      },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Male", "Female", "Other"],
        required: true,
        width: "half",
      },
      {
        name: "height",
        label: "Height (in cm)",
        type: "number",
        required: true,
        placeholder: "Enter height in centimeters",
        width: "half",
      },
      {
        name: "weight",
        label: "Weight (in kg)",
        type: "number",
        required: true,
        placeholder: "Enter weight in kilograms",
        width: "half",
      },
      {
        name: "email",
        label: "Email Address",
        type: "email",
        required: true,
        placeholder: "Enter your email",
        width: "full",
      },
      {
        name: "phoneNumber",
        label: "Phone Number",
        type: "text",
        required: true,
        placeholder: "Enter your phone number",
        width: "full",
      },
      {
        name: "location",
        label: "Location and Time Zone",
        type: "text",
        required: true,
        placeholder: "Enter your location and time zone",
        width: "full",
      },
    ],
  },
  {
    title: "Fitness Goals",
    fields: [
      {
        name: "fitnessGoals",
        label: "What are your primary fitness goals?",
        type: "checkbox",
        options: [
          "Weight loss",
          "Muscle building",
          "Improved strength",
          "Better endurance",
          "Improved flexibility",
          "Pain or injury management",
          "General health and fitness",
          "Other",
        ],
        required: true,
        width: "full",
      },
      {
        name: "motivation",
        label: "What motivates you to achieve this goal?",
        type: "textarea",
        required: true,
        placeholder: "Describe your motivation",
        width: "full",
      },
      {
        name: "resultsTimeline",
        label: "How soon are you looking to see noticeable results?",
        type: "text",
        required: true,
        placeholder: "Enter your timeline",
        width: "full",
      },
    ],
  },
  {
    title: "Medical History",
    fields: [
      {
        name: "medicalConditions",
        label: "Do you have any medical conditions, injuries, or chronic pain?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "medicalDetails",
        label: "If yes, please provide details",
        type: "textarea",
        required: false,
        placeholder: "Describe any medical conditions",
        width: "full",
      },
      {
        name: "medications",
        label: "Are you currently taking any medications?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "medicationDetails",
        label: "If yes, please list them",
        type: "textarea",
        required: false,
        placeholder: "List medications",
        width: "full",
      },
      {
        name: "surgeries",
        label: "Have you undergone any recent surgeries or treatments?",
        type: "textarea",
        required: false,
        placeholder: "Provide details of surgeries or treatments",
        width: "full",
      },
      {
        name: "foodAllergies",
        label: "Do you have any food allergies or intolerances?",
        type: "textarea",
        required: false,
        placeholder: "List food allergies or intolerances",
        width: "full",
      },
    ],
  },
  {
    title: "Current Lifestyle and Fitness Routine",
    fields: [
      {
        name: "lifestyleActivity",
        label: "How active is your current lifestyle?",
        type: "select",
        options: [
          "Sedentary (little or no exercise)",
          "Lightly active (light exercise 1-2 days/week)",
          "Moderately active (moderate exercise 3-4 days/week)",
          "Very active (hard exercise 5+ days/week)",
        ],
        required: true,
        width: "full",
      },
      {
        name: "fitnessExperience",
        label: "Do you have any prior experience with fitness training?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "fitnessDetails",
        label: "If yes, what kind (e.g., gym workouts, running, yoga)?",
        type: "textarea",
        required: false,
        placeholder: "Provide details of fitness experience",
        width: "full",
      },
      {
        name: "routineConsistency",
        label: "How consistent are you with your current fitness routine?",
        type: "text",
        required: true,
        placeholder: "Describe your consistency",
        width: "full",
      },
      {
        name: "exerciseTime",
        label: "What time of the day do you prefer to exercise?",
        type: "select",
        options: ["Morning", "Afternoon", "Evening", "Night"],
        required: true,
        width: "full",
      },
    ],
  },
  {
    title: "Dietary Preferences",
    fields: [
      {
        name: "dietType",
        label: "What is your typical diet like?",
        type: "text",
        required: true,
        placeholder: "e.g., vegetarian, non-vegetarian, vegan",
        width: "full",
      },
      {
        name: "dietaryPractices",
        label: "Do you follow any specific dietary practices or restrictions?",
        type: "textarea",
        required: false,
        placeholder: "List dietary practices or restrictions",
        width: "full",
      },
      {
        name: "mealsPerDay",
        label: "How many meals and snacks do you typically have in a day?",
        type: "number",
        required: true,
        placeholder: "Enter number of meals/snacks",
        width: "full",
      },
      {
        name: "favoriteFoods",
        label: "What are your favorite foods or cuisines?",
        type: "textarea",
        required: false,
        placeholder: "List favorite foods or cuisines",
        width: "full",
      },
      {
        name: "dislikedFoods",
        label: "Are there any foods you dislike or wish to avoid?",
        type: "textarea",
        required: false,
        placeholder: "List disliked foods",
        width: "full",
      },
    ],
  },
  {
    title: "Training Preferences",
    fields: [
      {
        name: "equipmentAccess",
        label: "Do you have access to any fitness equipment at home?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
      {
        name: "equipmentDetails",
        label: "If yes, please specify",
        type: "textarea",
        required: false,
        placeholder: "List fitness equipment",
        width: "full",
      },
      {
        name: "workoutTime",
        label: "How much time can you dedicate to workouts daily?",
        type: "text",
        required: true,
        placeholder: "Enter time in minutes/hours",
        width: "full",
      },
      {
        name: "trainingStyle",
        label: "Do you have any specific preferences for training styles?",
        type: "textarea",
        required: false,
        placeholder: "e.g., HIIT, yoga, strength training",
        width: "full",
      },
      {
        name: "dislikedExercises",
        label:
          "Are there any exercises or movements you dislike or find uncomfortable?",
        type: "textarea",
        required: false,
        placeholder: "List disliked exercises",
        width: "full",
      },
    ],
  },
  {
    title: "Expectations from Online Training",
    fields: [
      {
        name: "trainingExpectations",
        label: "What do you expect from your online personal training program?",
        type: "checkbox",
        options: [
          "Personalized workout plans",
          "Nutrition guidance",
          "Regular check-ins",
          "Progress tracking",
          "Other",
        ],
        required: true,
        width: "full",
      },
      {
        name: "communicationPreference",
        label: "How would you like to communicate with your trainer?",
        type: "text",
        required: true,
        placeholder: "e.g., video calls, chat, email",
        width: "full",
      },
      {
        name: "challenges",
        label:
          "What challenges do you think might affect your fitness journey?",
        type: "textarea",
        required: false,
        placeholder: "Describe challenges",
        width: "full",
      },
    ],
  },
  {
    title: "Expectations from Online Training",
    fields: [
      {
        name: "trainingExpectations",
        label: "What do you expect from your online personal training program?",
        type: "checkbox",
        options: [
          "Personalized workout plans",
          "Nutrition guidance",
          "Regular check-ins",
          "Progress tracking",
          "Other",
        ],
        required: true,
        width: "full",
      },
      {
        name: "communicationPreference",
        label: "How would you like to communicate with your trainer?",
        type: "text",
        required: true,
        placeholder: "e.g., video calls, chat, email",
        width: "full",
      },
      {
        name: "challenges",
        label:
          "What challenges do you think might affect your fitness journey?",
        type: "textarea",
        required: false,
        placeholder: "e.g., time constraints, motivation, etc.",
        width: "full",
      },
    ],
  },
  {
    title: "Lifestyle & Routine",
    fields: [
      {
        name: "typicalDay",
        label:
          "What does a typical day look like for you? (Work hours, physical activities, etc.)",
        type: "textarea",
        required: true,
        placeholder: "e.g., 9 AM - 5 PM work, 1-hour gym in the evening",
        width: "full",
      },
      {
        name: "sleepHours",
        label: "How many hours of sleep do you get on average per night?",
        type: "text",
        required: true,
        placeholder: "e.g., 6-8 hours",
        width: "half",
      },
      {
        name: "sleepSchedule",
        label:
          "What is your usual sleep schedule? (Time you go to bed and wake up)",
        type: "text",
        required: true,
        placeholder: "e.g., 10 PM - 6 AM",
        width: "half",
      },
      {
        name: "wakeUpFeeling",
        label:
          "How do you usually feel when you wake up? (Refreshed, tired, etc.)",
        type: "text",
        required: true,
        placeholder: "e.g., refreshed, tired, groggy",
        width: "full",
      },
      {
        name: "exerciseFrequency",
        label:
          "How often do you exercise or engage in physical activity? (Type and frequency)",
        type: "textarea",
        required: true,
        placeholder: "e.g., 3 days a week, strength training, yoga",
        width: "full",
      },
      {
        name: "workoutChallenges",
        label:
          "Do you face any challenges with maintaining a consistent workout routine?",
        type: "textarea",
        required: false,
        placeholder: "e.g., lack of time, injuries",
        width: "full",
      },
      {
        name: "sedentaryLifestyle",
        label: "Do you have a sedentary job or lifestyle?",
        type: "radio",
        options: ["Yes", "No"],
        required: true,
        width: "full",
      },
    ],
  },
  {
    title: "Dietary Preferences & Habits",
    fields: [
      {
        name: "dietType",
        label:
          "Are you vegetarian, non-vegetarian, vegan, or follow another specific diet?",
        type: "radio",
        options: ["Vegetarian", "Non-Vegetarian", "Vegan", "Other"],
        required: true,
        width: "full",
      },
      {
        name: "foodPreferences",
        label:
          "What types of foods do you like or dislike? (e.g., spicy, sweet, savory)",
        type: "textarea",
        required: true,
        placeholder: "e.g., love sweet foods, dislike spicy",
        width: "full",
      },
      {
        name: "typicalMeals",
        label:
          "What are your typical meals during the day? (Breakfast, lunch, dinner, snacks)",
        type: "textarea",
        required: true,
        placeholder:
          "e.g., eggs for breakfast, salad for lunch, pasta for dinner",
        width: "full",
      },
      {
        name: "eatingOut",
        label: "Do you often eat out or cook at home?",
        type: "radio",
        options: ["Eat out", "Cook at home"],
        required: true,
        width: "full",
      },
      {
        name: "mealFrequency",
        label: "Do you prefer smaller, frequent meals or larger meals?",
        type: "radio",
        options: ["Smaller, frequent meals", "Larger meals"],
        required: true,
        width: "full",
      },
      {
        name: "dietarySupplements",
        label:
          "Do you consume any dietary supplements? (Protein, vitamins, etc.)",
        type: "text",
        required: false,
        placeholder: "e.g., whey protein, multivitamins",
        width: "full",
      },
      {
        name: "foodAllergies",
        label:
          "Do you have any food allergies or intolerances? (e.g., gluten, dairy)",
        type: "textarea",
        required: false,
        placeholder: "e.g., lactose intolerant",
        width: "full",
      },
      {
        name: "digestiveIssues",
        label:
          "Do you have any digestive issues? (Indigestion, bloating, acid reflux, etc.)",
        type: "textarea",
        required: false,
        placeholder: "e.g., frequent bloating",
        width: "full",
      },
      {
        name: "alcoholOrSmoke",
        label: "Do you drink alcohol or smoke? (If yes, how often?)",
        type: "textarea",
        required: false,
        placeholder: "e.g., drink occasionally, no smoking",
        width: "full",
      },
    ],
  },
];
