const healthQustion = [
  {
    id: "firstName",
    name: "",
    label: "First Name",
    type: "text",
    placeholder: "e.g., John",
    width: "half",
    required: true,
  },
  {
    id: "lastName",
    name: "",
    label: "Last Name",
    type: "text",
    placeholder: "e.g., Doe",
    width: "half",
    required: true,
  },
  {
    id: "email",
    name: "",
    label: "Email",
    type: "email",
    placeholder: "e.g., john.doe@example.com",
    width: "half",
    required: true,
  },
  {
    id: "phone",
    name: "",
    label: "Phone Number",
    type: "tel",
    placeholder: "e.g., +123456789",
    width: "half",
    required: true,
  },
  {
    id: "bio",
    name: "",
    label: "Bio Data",
    type: "textarea",
    placeholder: "Write a short bio...",
    width: "full",
    required: true,
  },
  {
    id: "age",
    name: "",
    label: "Age",
    type: "number",
    placeholder: "e.g., 30",
    width: "half",
  },
  {
    id: "gender",
    name: "",
    label: "Gender",
    type: "text",
    placeholder: "e.g., Male/Female/Other",
    width: "half",
  },
  {
    id: "height",
    name: "",
    label: "Height (cm)",
    type: "number",
    placeholder: "e.g., 170",
    width: "half",
  },
  {
    id: "weight",
    name: "",
    label: "Weight (kg)",
    type: "number",
    placeholder: "e.g., 70",
    width: "half",
  },
  {
    id: "medicalConditions",
    name: "",
    label: "Medical Conditions",
    type: "textarea",
    placeholder: "List any medical conditions...",
    width: "full",
  },
  {
    id: "dietaryPreferences",
    name: "",
    label: "Dietary Preferences",
    type: "textarea",
    placeholder: "e.g., Vegetarian, Keto, etc.",
    width: "full",
  },
  {
    id: "exerciseFrequency",
    name: "",
    label: "Exercise Frequency",
    type: "text",
    placeholder: "e.g., 3 times per week",
    width: "half",
  },
  {
    id: "allergies",
    name: "",
    label: "Allergies",
    type: "textarea",
    placeholder: "e.g., Peanuts, Shellfish, etc.",
    width: "full",
  },
  {
    id: "smoker",
    name: "",
    label: "Do you smoke?",
    type: "radio",
    options: ["Yes", "No"],
    width: "half",
  },
  {
    id: "alcohol",
    name: "",
    label: "Do you consume alcohol?",
    type: "radio",
    options: ["Yes", "No"],
    width: "half",
  },
  {
    id: "activityLevel",
    name: "",
    label: "Activity Level",
    type: "select",
    options: [
      "Sedentary",
      "Lightly Active",
      "Moderately Active",
      "Very Active",
    ],
    width: "full",
  },
  {
    id: "preferences",
    name: "",
    label: "Preferences",
    type: "checkbox",
    options: [
      "Morning Workouts",
      "Evening Workouts",
      "Group Classes",
      "Personal Training",
    ],
    width: "full",
  },
];

export default healthQustion;
